version: '3.9'
services:
  mysql-travel:
    container_name: mysql-travel
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=travel_2023
      - MYSQL_PASSWORD=travel_2023
      - MYSQL_USER=travel
      - MYSQL_DATABASE=travel
    volumes:
      - ./mysqlDB:/var/lib/meinsql/data
  phpmyadmin-travel:
    image: phpmyadmin/phpmyadmin
    container_name: pma-travel
    depends_on:
        - mysql-travel
    environment:
        PMA_HOST: mysql-travel
    restart: always
    ports:
        - 8080:80